version: "3"

services:
  ganache:
    image: trufflesuite/ganache-cli:v6.4.1 
    ports:
      - "8545:8545"
    command: ["-a 3", "-e 100", "-b 10"]
  agents:
    build: .
    depends_on:
      - ganache 
    